// Shared helpers for "radio": turning a media item into a dynamic radio playlist.
//
// A radio is just a dynamic playlist generated by the server's built-in
// `radio_playlist` provider from a seed item (the seed's own tracks plus similar
// tracks). The "Go to <type> Radio" action navigates to that playlist's details
// view, where it behaves like any dynamic playlist (sample / enqueue / add to
// library).
import api from "@/plugins/api";
import {
  MediaItemTypeOrItemMapping,
  MediaType,
  Playlist,
  ProviderFeature,
} from "@/plugins/api/interfaces";
import router from "@/plugins/router";
import { store } from "@/plugins/store";

// Provider domain of the built-in radio-playlist generator. A radio playlist is
// addressed as `radio_playlist://playlist/<seed item uri>`.
const RADIO_PLAYLIST_PROVIDER = "radio_playlist";

// Media types that can seed a radio playlist.
const RADIO_SEED_TYPES = [
  MediaType.TRACK,
  MediaType.ARTIST,
  MediaType.ALBUM,
  MediaType.PLAYLIST,
  MediaType.GENRE,
];

// Per-type i18n key for the "Go to <type> Radio" action label.
const RADIO_LABEL_KEYS: Partial<Record<MediaType, string>> = {
  [MediaType.ARTIST]: "goto_artist_radio",
  [MediaType.ALBUM]: "goto_album_radio",
  [MediaType.TRACK]: "goto_track_radio",
  [MediaType.PLAYLIST]: "goto_playlist_radio",
  [MediaType.GENRE]: "goto_genre_radio",
};

// Translation key for the radio action label, specific to the item's media type.
export const radioActionLabelKey = (item: MediaItemTypeOrItemMapping): string =>
  RADIO_LABEL_KEYS[item.media_type] ?? "goto_radio";

// Whether the item is a type that can seed a radio playlist. Used to decide
// whether to surface the radio action at all (it shows disabled when the type is
// relevant but a radio can't currently be generated). A dynamic playlist already
// owns its own track feed, so radio doesn't apply.
export const radioRelevant = (item: MediaItemTypeOrItemMapping): boolean => {
  if (!RADIO_SEED_TYPES.includes(item.media_type)) return false;
  if (item.media_type === MediaType.PLAYLIST && (item as Playlist).is_dynamic) {
    return false;
  }
  return true;
};

// Whether a radio playlist can actually be generated from the given item right
// now: a relevant type whose provider can supply similar tracks.
export const radioSupported = (item: MediaItemTypeOrItemMapping): boolean => {
  if (!radioRelevant(item)) return false;
  // genres are generated server-side and don't rely on a similar-tracks provider
  if (item.media_type === MediaType.GENRE) return true;
  if ("provider_mappings" in item) {
    for (const provId of item.provider_mappings) {
      if (
        api.providers[provId.provider_instance]?.supported_features.includes(
          ProviderFeature.SIMILAR_TRACKS,
        )
      )
        return true;
    }
  } else if (
    api.providers[item.provider]?.supported_features.includes(
      ProviderFeature.SIMILAR_TRACKS,
    )
  ) {
    return true;
  }
  // generic radio: any provider supports similar tracks and the item is
  // (matched) in the library
  if (item.provider === "library") {
    for (const prov of Object.values(api.providers)) {
      if (prov.supported_features.includes(ProviderFeature.SIMILAR_TRACKS))
        return true;
    }
  }
  return false;
};

// Open the item's radio in the (dynamic-aware) playlist details view, where it
// can be sampled, enqueued or added to the library like any dynamic playlist.
export const gotoRadio = (item: MediaItemTypeOrItemMapping): void => {
  store.showFullscreenPlayer = false;
  router.push({
    name: "playlist",
    params: { provider: RADIO_PLAYLIST_PROVIDER, itemId: item.uri },
  });
};
