// Generated by scripts/sync-shared-icons.mjs from shared-icons 1.0.0 (4db35f18e7c5166bf26b5cd89b0fa27ea53786c5). Do not edit.
import { makeSvgIcon } from "./_make-icon";
import type { Component } from "vue";

import icon_homepod_mini from "@/vendor/shared-icons/icons/homepod-mini.svg?raw";
import icon_sonos from "@/vendor/shared-icons/icons/sonos.svg?raw";
import icon_mac from "@/vendor/shared-icons/icons/mac.svg?raw";
import icon_apple_tv from "@/vendor/shared-icons/icons/apple-tv.svg?raw";
import icon_google_nest from "@/vendor/shared-icons/icons/google-nest.svg?raw";
import icon_voice_pe from "@/vendor/shared-icons/icons/voice-pe.svg?raw";
import icon_wiim from "@/vendor/shared-icons/icons/wiim.svg?raw";
import icon_speaker from "@/vendor/shared-icons/icons/speaker.svg?raw";
import icon_speakers from "@/vendor/shared-icons/icons/speakers.svg?raw";
import icon_soundbar from "@/vendor/shared-icons/icons/soundbar.svg?raw";
import icon_radio from "@/vendor/shared-icons/icons/radio.svg?raw";
import icon_tv from "@/vendor/shared-icons/icons/tv.svg?raw";
import icon_monitor from "@/vendor/shared-icons/icons/monitor.svg?raw";
import icon_laptop from "@/vendor/shared-icons/icons/laptop.svg?raw";
import icon_smartphone from "@/vendor/shared-icons/icons/smartphone.svg?raw";
import icon_tablet from "@/vendor/shared-icons/icons/tablet.svg?raw";
import icon_headphones from "@/vendor/shared-icons/icons/headphones.svg?raw";
import icon_bluetooth from "@/vendor/shared-icons/icons/bluetooth.svg?raw";
import icon_airplay from "@/vendor/shared-icons/icons/airplay.svg?raw";
import icon_cast from "@/vendor/shared-icons/icons/cast.svg?raw";
import icon_car from "@/vendor/shared-icons/icons/car.svg?raw";
import icon_music from "@/vendor/shared-icons/icons/music.svg?raw";
import icon_vinyl from "@/vendor/shared-icons/icons/vinyl.svg?raw";
import icon_mic from "@/vendor/shared-icons/icons/mic.svg?raw";
import icon_volume from "@/vendor/shared-icons/icons/volume.svg?raw";
import icon_living_room from "@/vendor/shared-icons/icons/living-room.svg?raw";
import icon_bedroom from "@/vendor/shared-icons/icons/bedroom.svg?raw";
import icon_bathroom from "@/vendor/shared-icons/icons/bathroom.svg?raw";
import icon_toilet from "@/vendor/shared-icons/icons/toilet.svg?raw";
import icon_kitchen from "@/vendor/shared-icons/icons/kitchen.svg?raw";
import icon_office from "@/vendor/shared-icons/icons/office.svg?raw";
import icon_hallway from "@/vendor/shared-icons/icons/hallway.svg?raw";
import icon_garden from "@/vendor/shared-icons/icons/garden.svg?raw";
import icon_outdoor from "@/vendor/shared-icons/icons/outdoor.svg?raw";
import icon_sun from "@/vendor/shared-icons/icons/sun.svg?raw";
import icon_home from "@/vendor/shared-icons/icons/home.svg?raw";
import icon_building from "@/vendor/shared-icons/icons/building.svg?raw";

export const registry: Record<string, Component> = {
  "homepod-mini": makeSvgIcon("homepod-mini", icon_homepod_mini),
  sonos: makeSvgIcon("sonos", icon_sonos),
  mac: makeSvgIcon("mac", icon_mac),
  "apple-tv": makeSvgIcon("apple-tv", icon_apple_tv),
  "google-nest": makeSvgIcon("google-nest", icon_google_nest),
  "voice-pe": makeSvgIcon("voice-pe", icon_voice_pe),
  wiim: makeSvgIcon("wiim", icon_wiim),
  speaker: makeSvgIcon("speaker", icon_speaker),
  speakers: makeSvgIcon("speakers", icon_speakers),
  soundbar: makeSvgIcon("soundbar", icon_soundbar),
  radio: makeSvgIcon("radio", icon_radio),
  tv: makeSvgIcon("tv", icon_tv),
  monitor: makeSvgIcon("monitor", icon_monitor),
  laptop: makeSvgIcon("laptop", icon_laptop),
  smartphone: makeSvgIcon("smartphone", icon_smartphone),
  tablet: makeSvgIcon("tablet", icon_tablet),
  headphones: makeSvgIcon("headphones", icon_headphones),
  bluetooth: makeSvgIcon("bluetooth", icon_bluetooth),
  airplay: makeSvgIcon("airplay", icon_airplay),
  cast: makeSvgIcon("cast", icon_cast),
  car: makeSvgIcon("car", icon_car),
  music: makeSvgIcon("music", icon_music),
  vinyl: makeSvgIcon("vinyl", icon_vinyl),
  mic: makeSvgIcon("mic", icon_mic),
  volume: makeSvgIcon("volume", icon_volume),
  "living-room": makeSvgIcon("living-room", icon_living_room),
  bedroom: makeSvgIcon("bedroom", icon_bedroom),
  bathroom: makeSvgIcon("bathroom", icon_bathroom),
  toilet: makeSvgIcon("toilet", icon_toilet),
  kitchen: makeSvgIcon("kitchen", icon_kitchen),
  office: makeSvgIcon("office", icon_office),
  hallway: makeSvgIcon("hallway", icon_hallway),
  garden: makeSvgIcon("garden", icon_garden),
  outdoor: makeSvgIcon("outdoor", icon_outdoor),
  sun: makeSvgIcon("sun", icon_sun),
  home: makeSvgIcon("home", icon_home),
  building: makeSvgIcon("building", icon_building),
};

export const Speakers = registry["speakers"];
