#!/bin/sh
# Pushes a new version to PyPi.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

# Install node modules
yarn install

# Run build
yarn build

rm -rf dist music_assistant_frontend.egg-info
python3 -m build
python3 -m twine upload dist/*.whl --skip-existing