export const CONFIG_KEY = {
  ONBOARD_DONE: "onboard_done",
  SERVER_ID: "server_id",
  IP_ADDRESS: "ip_address",
  PORT: "port",
  PROVIDERS: "providers",
  PLAYERS: "players",
  CORE: "core",
  PATH: "path",
  NAME: "name",
  USERNAME: "username",
  PASSWORD: "password",
  VOLUME_NORMALIZATION: "volume_normalization",
  VOLUME_NORMALIZATION_TARGET: "volume_normalization_target",
  OUTPUT_LIMITER: "output_limiter",
  DEPRECATED_EQ_BASS: "eq_bass",
  DEPRECATED_EQ_MID: "eq_mid",
  DEPRECATED_EQ_TREBLE: "eq_treble",
  PLAYER_DSP: "player_dsp",
  PLAYER_DSP_PRESETS: "player_dsp_presets",
  OUTPUT_CHANNELS: "output_channels",
  FLOW_MODE: "flow_mode",
  LOG_LEVEL: "log_level",
  HIDE_GROUP_CHILDS: "hide_group_childs",
  CROSSFADE_DURATION: "crossfade_duration",
  BIND_IP: "bind_ip",
  BIND_PORT: "bind_port",
  PUBLISH_IP: "publish_ip",
  AUTO_PLAY: "auto_play",
  DEPRECATED_CROSSFADE: "crossfade",
  GROUP_MEMBERS: "group_members",
  DYNAMIC_GROUP_MEMBERS: "dynamic_members",
  HIDE_PLAYER_IN_UI: "hide_player_in_ui",
  EXPOSE_PLAYER_TO_HA: "expose_player_to_ha",
  SYNC_ADJUST: "sync_adjust",
  TTS_PRE_ANNOUNCE: "tts_pre_announce",
  ANNOUNCE_VOLUME_STRATEGY: "announce_volume_strategy",
  ANNOUNCE_VOLUME: "announce_volume",
  ANNOUNCE_VOLUME_MIN: "announce_volume_min",
  ANNOUNCE_VOLUME_MAX: "announce_volume_max",
  PRE_ANNOUNCE_CHIME_URL: "pre_announcement_chime_url",
  ICON: "icon",
  LANGUAGE: "language",
  SAMPLE_RATES: "sample_rates",
  HTTP_PROFILE: "http_profile",
  BYPASS_NORMALIZATION_RADIO: "bypass_normalization_radio",
  ENABLE_ICY_METADATA: "enable_icy_metadata",
  VOLUME_NORMALIZATION_RADIO: "volume_normalization_radio",
  VOLUME_NORMALIZATION_TRACKS: "volume_normalization_tracks",
  VOLUME_NORMALIZATION_FIXED_GAIN_RADIO:
    "volume_normalization_fixed_gain_radio",
  VOLUME_NORMALIZATION_FIXED_GAIN_TRACKS:
    "volume_normalization_fixed_gain_tracks",
  POWER_CONTROL: "power_control",
  VOLUME_CONTROL: "volume_control",
  MUTE_CONTROL: "mute_control",
  OUTPUT_CODEC: "output_codec",
  ALLOW_AUDIO_CACHE: "allow_audio_cache",
  SMART_FADES_MODE: "smart_fades_mode",
  USE_SSL: "use_ssl",
  VERIFY_SSL: "verify_ssl",
  SSL_FINGERPRINT: "ssl_fingerprint",
  AUTH_ALLOW_SELF_REGISTRATION: "auth_allow_self_registration",
  ZEROCONF_INTERFACES: "zeroconf_interfaces",
  ENABLED: "enabled",
} as const;

export type ConfigKey = (typeof CONFIG_KEY)[keyof typeof CONFIG_KEY];
